- name: Update package cache (Ubuntu)
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Update package cache (AlmaLinux)
  ansible.builtin.dnf:
    update_cache: true
  when: ansible_os_family == "RedHat"
